import Navbar from './components/Navbar/Navbar';
import './styles/global.css';
import { startSimulationLoop } from '@/lib/backgroundSimulation';


startSimulationLoop();

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        {children}
        </body>
    </html>
  )
}
